services:
  maths_crew:
    build: ./maths_crew
    environment:
      - OPENAI_API_BASE=http://host.docker.internal:11434
      - OPENAI_MODEL_NAME=ollama/llama3.1
      - OPENAI_API_KEY=ollama
    # deploy:
    #   replicas: 10  # You can increase the number of replicas to scale

  writing_crew:
    build: ./writting_crew
    environment:
      - OPENAI_API_BASE=http://host.docker.internal:11434
      - OPENAI_MODEL_NAME=ollama/llama3.1
      - OPENAI_API_KEY=ollama

  # crewai-app3:
  #   build: .
  #   environment:
  #     - OPENAI_API_BASE=http://host.docker.internal:11434
  #     - OPENAI_MODEL_NAME=ollama/llama3.1
  #     - OPENAI_API_KEY=ollama
